### ISSUE TITLE
How to compile src code on Windows

### ISSUE THREAD

**Issue by Photron-Nagai** [USAMAWIZARD/AntMedia-Gstreamer-Webrtc#1]
In readme.md there are only way to compile src code on Linux and Mac.
How to compile src code on Windows?

**Comment by USAMAWIZARD** [comment]
gcc ./sendRecvAnt.c  -o  sendRecvAnt  ` pkg-config --cflags --libs gstreamer-1.0 gstreamer-webrtc-1.0 gstreamer-sdp-1.0  json-glib-1.0 `  ./libs/win64_x86_librws.lib

**Comment by USAMAWIZARD** [comment]
@Photron-Nagai  please let me know if this works then I will update the docs

**Comment by Photron-Nagai** [comment]
@USAMAWIZARD 
I ran the following command on Windows 10 after installing Gstreamer.
`gcc ./sendRecvAnt.c -o sendRecvAnt pkg-config --cflags --libs gstreamer-1.0 gstreamer-webrtc-1.0 gstreamer-sdp-1.0 json-glib-1.0 ./libs/win64_x86_librws.lib`

and got errors
```
./sendRecvAnt.c: In function 'on_socket_received_text':
./sendRecvAnt.c:325:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
./sendRecvAnt.c:356:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
                 answersdp = gst_webrtc_session_description_new(GST_WEBRTC_SDP_TYPE_ANSWER, sdp);
                           ^
./sendRecvAnt.c:365:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
./sendRecvAnt.c:379:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
c:/gstreamer/1.0/msvc_x86_64/lib/libmingw32.a: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
```
Do you have any solutions?
My enverionment is below.

> OS : Windows10
> Gstreamer : Version 1.22.4
> GCC : Version 6.3.0

**Comment by USAMAWIZARD** [comment]
it should work we can have a call if you can let me know your availability

**Comment by USAMAWIZARD** [comment]
``` gcc ./sendRecvAnt.c -o sendRecvAnt pkg-config --cflags --libs `gstreamer-1.0 gstreamer-webrtc-1.0 gstreamer-sdp-1.0 json-glib-1.0`  ./libs/win64_x86_librws.lib  ```

**Comment by Photron-Nagai** [comment]
@USAMAWIZARD 
I'm available now.

**Comment by USAMAWIZARD** [comment]
I am available at 8 PM IST today let me know if that works for you
it will be approximately 2 hrs from now

**Comment by Photron-Nagai** [comment]
@USAMAWIZARD 

I tried but it does not work properly.
> `` gcc ./sendRecvAnt.c -o sendRecvAnt pkg-config --cflags --libs `gstreamer-1.0 gstreamer-webrtc-1.0 gstreamer-sdp-1.0 json-glib-1.0` ./libs/win64_x86_librws.lib ``

```
> sh: gstreamer-1.0: command not found
> gcc.exe: error: pkg-config: No such file or directory
> gcc.exe: error: unrecognized command line option '--cflags'
> gcc.exe: error: unrecognized command line option '--libs'
```

I think the below command is right but same errors happend.
> `` gcc ./sendRecvAnt.c -o sendRecvAnt `pkg-config --cflags --libs gstreamer-1.0 gstreamer-webrtc-1.0 gstreamer-sdp-1.0 json-glib-1.0` ./libs/win64_x86_librws.lib ``

```
./sendRecvAnt.c: In function 'on_socket_received_text':
./sendRecvAnt.c:325:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
./sendRecvAnt.c:356:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
                 answersdp = gst_webrtc_session_description_new(GST_WEBRTC_SDP_TYPE_ANSWER, sdp);
                           ^
./sendRecvAnt.c:365:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
./sendRecvAnt.c:379:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             webrtcbin_id = json_object_get_string_member(object, "streamId");
                          ^
c:/gstreamer/1.0/msvc_x86_64/lib/libmingw32.a: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
```

**Comment by USAMAWIZARD** [comment]
are you using 32 bit windows ?
also please use mingw compiler for windows
or else lets connect at 8:00 PM IST if you are avaialble

**Comment by USAMAWIZARD** [comment]
also please use mingw compiler for windows

**Comment by Photron-Nagai** [comment]
> 

No I use 64 bit windows.
I installed gcc from mingw (https://sourceforge.net/projects/mingw/) which should be installer for 64 bit windows.

**Comment by USAMAWIZARD** [comment]
this may be the issue with the websocket library 
try building this library from src https://github.com/OlehKulykov/librws
and replace the file lib file in the command

**Comment by Photron-Nagai** [comment]
> this may be the issue with the websocket library try building this library from src https://github.com/OlehKulykov/librws and replace the file lib file in the command

Thanks.
I will try it and tell you the result.

**Comment by USAMAWIZARD** [comment]
Hi @Photron-Nagai Did it worked for you ?

**Comment by Photron-Nagai** [comment]
I could build on Visual Studio Project but I'm not sure that executable file work correctly. 
That always returns WebSocket connection closed.

Sending stream
```
>sendRecvAnt.exe --ip 127.0.0.1 -i QkDFGLjl4tTHBJ0x1689656234595
start 127.0.0.1  5080 WebSocket connection closed
```

Receiving stream
```
>sendRecvAnt.exe --ip 127.0.0.1 --mode play -i QkDFGLjl4tTHBJ0x1689656234595
start 127.0.0.1  5080 WebSocket connection closed
```

I created LiveApp in AntMediaServer on local machine with WSL before executed 「sendRecvAnt.exe」on command prompt on Windows10.

**Comment by USAMAWIZARD** [comment]
are you able to access the port 5080 from your host machine ?
are you using community or enterprise ?
please use WebRTCAppEE application

**Comment by Photron-Nagai** [comment]
I can access the port 5080 and create WebRTCAppEE application with community edition.

**Comment by USAMAWIZARD** [comment]
WebRTC play is not supported with community edition

**Comment by USAMAWIZARD** [comment]
is publishing working now ? if possible can you please send a PR for the build file and replace the file in lib directry with your build file [win64_x86_librws.lib](https://github.com/USAMAWIZARD/AntMedia-Gstreamer-Webrtc/blob/master/libs/win64_x86_librws.lib)

**Comment by ajlennon** [comment]
I've put together a cmake build that we've just checked works on Windows

https://github.com/USAMAWIZARD/AntMedia-Gstreamer-Webrtc/issues/2

**Comment by USAMAWIZARD** [comment]
Thanks @ajlennon  , then I will close this issue feel free to re open the issue if you face the proble
