### ISSUE TITLE
Question about PR for cmake support

### ISSUE THREAD

**Issue by ajlennon** [USAMAWIZARD/AntMedia-Gstreamer-Webrtc#2]
Hi there!

Lovely example thanks. We're trying to use this on Chinese cameras with the OpenIPC.org firmware.

I wanted to try to integrate your example so I could get it cross-compiled but it was difficult without a make build system.

So I created a cmake configuration that builds the example (including a submodule for librws).

This works when building on Ubuntu and also works when cross-compiling within Buildroot / OpenIPC.

Would you be interested in a PR to add this cmake support in?

NB. Currently I've taken out the pre-built binaries and I don't know if that would cause a problem for you.

Cheers,

Alex

**Comment by ajlennon** [comment]
We've verifed this builds and works on Windows now.

**Comment by USAMAWIZARD** [comment]
Hi @ajlennon , 
Thank you very much for your contribution , Please raise a PR and I will merge it . [here](https://www.linkedin.com/in/usama-tahseen-ul-haque-325399160/) is my Linkedin , I would love to connect with you.

**Comment by ajlennon** [comment]
Thanks will do!

**Comment by ajlennon** [comment]
Thanks for merging that in - will close this issue

**Comment by USAMAWIZARD** [comment]
Hi @ajlennon , 
Thanks  I have merged the pr , [here](https://www.linkedin.com/in/usama-tahseen-ul-haque-325399160/) is my LinkedIn , I would love to connect with you.
